apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: traefik
spec:
  secretName: tls-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - <path:cert-manager:domain-config#domain>
    - <path:cert-manager:domain-config#wildcard>