apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - clusterissuer.yaml
  - configmap.yaml
  - certificate.yaml

replacements:
  - source:
      kind: ConfigMap
      name: domain-config
      fieldPath: data.domain
    targets:
      - select:
          kind: Certificate
          name: tls-cert
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: ConfigMap
      name: domain-config
      fieldPath: data.wildcard
    targets:
      - select:
          kind: Certificate
          name: tls-cert
        fieldPaths:
          - spec.dnsNames.1

helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts/cert-manager
    version: v1.19.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      crds:
        enabled: true
