apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_ingressroutes.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_ingressroutetcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_ingressrouteudps.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_middlewares.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_middlewaretcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_serverstransports.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_serverstransporttcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_tlsoptions.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_tlsstores.yaml
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v39.0.0/traefik/crds/traefik.io_traefikservices.yaml


helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 39.0.0
    releaseName: traefik
    namespace: traefik
    valuesInline:
      ports:
        traefik:
          expose:
            default: true
      ingressRoute:
        dashboard:
          enabled: true
        healthcheck:
          enabled: true
      service:
        type: LoadBalancer
        spec:
          loadBalancerIP: 192.168.202.101
