---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgBBoPvLon3fYOTdtD7smbfLJ96ojf63SAFfc9BLqQiwmS20bqyBvqsEjN2iO01m4VhJpLl3GkIpKDEM1OR7q9Xyd8Rs5CdmIWm90v44LpLWD0Tq3y+m9W6kTD833kSzhow4/1t5Pz2jZqANumhDl0U0PQM9LwCwUU6tKWOyXGhuqCq4yXl9Wq0uv+1ZKkO83eEoEPOKqL/GjGddujt2iUEPi1CRBQsciQf5v4RtFQlHu2UiHsIz4HOmmcwnTXIdfWN9zCWeYQob1CiVSgcvOyVkaiv/F5Exk7wGZnZuiwScKUkah04+4WX73LldbGGnAgXZ+D9kHScEk0iv0Mg1DS96U3wegiVxNytO4mzjFKx8X66J78OVb/4nDfdHfhUU61FLI7CVipr6FQTm2OSUczyo5lMZvAJwVW6xg2uDoWlTKTxGVgahcsuX3dCjkgcxT2jEffdKETx9z6w4j/YHRJkPUe+PaW+TnUqhcr334NjIiX4PJeNyGYWqmCfa7r601KmiSI3KvW7UX8CNyL78H+J2mUS3ZPNw97oTz6agSaYM+CY+6c5BWLR1VqT9LEkluRlilA+9iy970891IxDVJFfUcVR+z2wAT4AVA3nCCiQvrh2oN/Gjw8t8fh1Ut9HAvD/4gaK0Z8909LqKmm1cM3wrxiaRsMzXElDDsX7erXUvg+Z7b61NopeLn4qKXM+c7AWs8Dbh9FWrxU7pHE7czEKEO+SlwzxYh91nZIupYTCCEql91Po85D5QLsaB7HJBqha7KrN5WgCHIeoqPr3EqrQLYgxPust87krL6YeRk2/cZ6REdGghLN7X8OjF0F23fSHb0Hr5RljPtKbdjXn07SoE1CE/tBZr3qc58I8FDFRww0SAVAOmEKA=
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
    type: Opaque
