apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi
provisioner: csi.san.synology.com
parameters:
  fsType: 'ext4'
  dsm: '192.168.202.1'
  location: '/volume2'
reclaimPolicy: Retain
allowVolumeExpansion: true
