services:
  pocketid:
    container_name: pocketid
    image: ghcr.io/pocket-id/pocket-id:v2.2.0
    environment:
      APP_URL: ${APP_URL}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      TRUST_PROXY: true
    volumes:
      - /volume2/docker/pocketid/volumes/appdata:/app/data"
    ports:
      - "1411:1411"
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - prod_net

networks:
  prod_net:
    external: true