services:
  emailproxy:
    container_name: oauthmail
    image: blacktirion/email-oauth2-proxy-docker:2025.10.09
    environment:
      LOGFILE: true
      DEBUG: true
      CACHE_STORE: /config/credstore.config
      LOCAL_SERVER_AUTH: true
    volumes:
      - /volume2/docker/oauthmail/volumes/config:/config
    ports:
      - 1587:1587
      - 1588:1588
      - 1589:1589
    networks:
      - prod_net

networks:
  prod_net:
    external: true