services:
  oauthmail:
    container_name: oauthmail
    image: blacktirion/email-oauth2-proxy-docker:2026.01.06
    environment:
      LOGFILE: true
      DEBUG: true
      CACHE_STORE: /config/credstore.config
      LOCAL_SERVER_AUTH: true
    volumes:
      - /volume2/docker/oauthmail/volumes/config:/config
    ports:
      - 1587:1587 # Auth
      - 1588:1588 # SMTP
    networks:
      - prod_net

networks:
  prod_net:
    external: true