---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCxddXyOllx98XTTXs9lpFs4lgO/6pZgw4yZQxbeYbdVrJOjC26/tuAf6U2UkRPHU3VKNXiIzvjxZ5Y6OxKabeBGD7efVpXku5xgDIfQ0aC1BlzD3pXK8doeu/ojSgPld7SXIbwVeFdikp4tKiTzSZ+2KYVEgL0jLERAd25fgb9+M8wtVfN8oo9uyc0WxL/Y0cu/jB7sEWSTX1CY2mERPq9nuz0vPhomqS6eFG4qh7nprSSBtj7kTx34ypLkTt2U/7NMZvv339OCVPRkIEfn41jxpwuYawYB0GYqLKb3I0wd+OZPYa50/m+dXA3EnP4B3NGrUrxxUqD05nrA2xSvOwyEYFI0uS7PmoJG3wVI+cuI3bXGjq/V51MslbNGbI1yLipgCDI9+JI+P8fpIpfIyEmW5WN+JPrAFUkQwYS2DpX5YgpHSp6lmgQTqylW00ZSEGDDtTRWImFmLHYvlJPQUn1dX9oxoUETBQnzMKhL2TDOdFmUwcmMCVsgy6545/QsFB4jWD32H+FCf5pKb0kNQRZmbWD9ddLbCm1hjKdZIfb7mhJ73hta0cANMJ99ADJ2ca8SUePi9s6OJ1BnfPJJM+GJ9ub/z8Dk63aFscRPCHf3FpkNOK0X5vaigaYIUOITamzwRTvRC356r/Q7GsO0GJqT3f5kPo41XNgYEJGVDPi6tuNXQithq42AWHv9Sx3zm4bfAW+2QKCaLZB1Sv/HPwDjdZswURcPOUN6NGGyc6sVkhpU76EjgyR
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
