apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  type: ClusterIP
  ports:
    - port: 8191
      targetPort: 8191
      protocol: TCP
      name: http
    - port: 8192
      targetPort: 8192
      protocol: TCP
      name: metrics
  selector:
    app: flaresolverr
