---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgAlzZGjw0QqmeCmjSwQ8s0U0E/s+joTmDsa80kjPmqCRupAUrhLUDI+w3LKsGTHwWld3dQfte1nQ5d+ox2Gt3avvRtL2aYDAIvIDI5DMxYZpBD7fQ4C1JEb4EuOvF0MAg08ioqAsHAftgyXqUkq4K8lVn7q6nMJmtyVXnieqNEb3yoXmzQk3WmXFZaGostJK4jjZG7kn1qCRZWyLHKVrKw7ujZvAJOBplr+3UzQrbf4+3H2mEnm/E4rndqiOQ18lGRVRCspRgFA4WAeNizryWqvT16pQGDvxP1wdHFMfZB7NGr87UZQSFxW0pqa4GpM5uuaAiTAcmm8+Al9PQOHNA0CE86MFKwvK65UmOwIoYS5ebCGV9UTEHeeDlasXk13972+3CkkvTpBJ49v0TbDNUZxyJ5SNy3Sf9Iy4i4lHekMsDNp/yCZuZCem/GtgQ9B34iqirkDC09KU9sXkr8/VzvCZAoW6S1Ll7TmFSLIzEIMTvfL0xLDic6hnk15DDG3Gu6p0cMuM9MBRIYJlSBAia3q57PaokdMZK7MYFyFnyzYtKiqr8AkSU1aPAxf9y5tm7rfvuPHp05FIoN+D9rYSMzh0Qn+02csNSmdrX/ZFOHBqCYhK9VyRJkQSpUV7h75vWWKuDNyknZFM2KkJfL3tqNks3cV/BASNa9anvasQS+BG4kZ3viSBvQqE0j55KBpgwPIEJsDdfn21EAd+subZLKnqycq7VzBv+yMb+Ns8pTrcDOYCEANkThfD5h5JX9h
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
    type: Opaque
