---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgCuCRYXsS0xQYPaH1Kx8SxMQiuiYgYqO2GkZPu0XC4FOjyaXHAb2k8JP2PAm9f9bWSW05TlQULVXcUosjpLHild8zolTdf8DPaFvVZD8rfUL4dYkc0lu0PnnEPsS61LxZ4+2Rnxku/1UoKHO4S+c0y3ZcZwAlyUVop/bhwIEZjirNRvVOJZlPMQ1M5IaZey35IyEOeV6DcXhd9hp79+FXuqBPMz1SU0i9MnX/jjCmuqJrEQaG96CTGn8q3uT21AqnpTgWfHvZLNJ5j3drH/alvJXrl2m3hq/kNEa1ALW8+eHDpGuRFeSA1uBjK637Tye+EwCJFpAwc3bB+BFmrhnmEE2VgoSpTFIxXL7oOrnsUMTbjgV5e2zgbaMmPTKYIytWgQm+e1wUMagqUE3wBjNuo+qOwjJN5wUoREiLNNb4qmPBcJvyUfMiAPfdDzBS4FbkKFx/XUE0GmQXIjAFUKwBkAZEF5YuLdP16yLaMQIOZRaywwyus7Dmf0y0dstDQWy3bWQNHvrHd4ZNYn9GA7EAkeHOKDjYnj1QKcmaIxZ7RveCbxOoox/3pefAWyaZPYn4lli0mwuv2NCIT8vQQ19xmz57w8G09sdxYw4vy5wnQXXuUHhQd33G2yD/fEczypC5BlHD4Biks5ANCi/sYS+hhntYH5/UTl+UhaBuWtIJ2LTIzB3XqQpBPA8VKFxPBc05AhwHpVY1LojAG6q9nbCgYUrLM3F2CZ2MLRhT7slL84jP5kzWeZJGs4J5lw7cgo
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
    type: Opaque
