---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cf-metrics-scrape
  namespace: monitoring
spec:
  encryptedData:
    prometheus-additional-scrape-configs.yaml: AgA0oOE30JyWWGQ7x1WXHugERz9+EQdXGLJijIANsf7rmZKApumuhE1Usa3hAPS9TeWjp8mF5WfebepFCt73jD+Rf2Yh7LGbUSN0rZraqdJX/9Ia+e4MalPLQt7RP8G4On8wHXMbQuzxrWbUpDiw5glGzwEu9gkA7eLHVBEN2uGVGsPyddz91UEqq4WySl9OMyy3uH6K+nncHb/UjquzvdgOkzvlDYKzoIqQnBiSzm7R9gVdgE69+IMzUedvS7yP/8Y0YFsQ3tFnRckW8KuzUEm0PnQ+G/45m7FN7h9q1Bkb3a6rh5QjXf/hHp2p94JxnODHuxcR4kOTbOFTVIv8sbeDWfuGqGz79lGC4LLI1KB6pYPCrPQJtJrS+tqi7k24k9UQg/ebNRBiiAM73LecUkj5qp0y3g9SaRf2U6wiTNSl0uE2gW+VYKXrrRfOSChzUj/hPG3DuK2AVompXAVqkXmKOPRZVu6ol7sl0oq7evlP/d3dVPBonxlqQtMygUmO/18HJcWl77YsmpHQ4o6vFIHY1HOuDxB4Iss1Mul6pakNL0V9fPev7J9y1+4bpM2jhA3OTjWlMg8u3AljvUY/iKC1F6OCJ0bWoIwP97nUO3rcjKz/9130Inn09DsGYfNJa609CfAOh6g2pVu6kcRksPDExxdyZCo+qyQgPrjIltnut8qAN2DhcWEQZiJ1trKdBD7LPr/g8oq/wcgondZe+vj+auBBlNlsOzvM3T022y2iHfLETXYGLKKUF+pzC36eGQ2slv6ShuLD0YUnyXcLmR6EZbEYPJ84U/2KYOmFbxM9q5Fq3lIe2XaOaHUy1RrQ1u/YfAfzFhrri5dCL027yU3fivrY396hpPWOcI/4Qr0yxSfJ/wrFDkKUNtkWLkYBGsKQ2oV7gtfarkmg4NQ/m089sbYT2FEJkjGr8mQGc6EZk21Whmc7Xgxsnh6daX2GjKaeexP81mrRVsbSo5KuK7P/ivC9+Hkji6XjjUqzFwqWqh1SzKl4+D4VTDmJetzTXaKY9wf/2g1l8QdANxQuUV25lMRHdKKPlSnkMfdmX1tSEveQ1ZvLqA+IU1rIVYApXd0DAbAf/BN53fevEmtzFlA7gb0PtGqrZfgzARwUe3lwwNlIcSonuy6yRYAeThpjcygWhmwZT3dm4RMfD1HD+6b/lVQpJeBjJayNKRMYk1TWvZTIzno=
  template:
    metadata:
      name: cf-metrics-scrape
      namespace: monitoring
    type: Opaque
