---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBVrvV2OefxORw7p2xIyD5VXCfb6y+dvGpW2+iObSRTO2Abb8JIDBMcVHhGrWnbrWHxMSv5ww87CvsS93KX2expFvaGu3oIg0vb0acYo6OoI1umFSHl4Bbu4PdpxwIGZ1cTIbtclRJLTKHZPlbUmdcBwmqqj0NYfh+cEjipgJt3PWhzJiseM8fYYeUUfAe6vjWuJPMwZE+6tjS54Gj7FNm3LXk6FfqUxQJ/Gp+1/XlZiYhA8+t8sYMwGOWmLzgRG37icVJj0J4IYpOw8cSi9ZJluyhlKoO348RwZEseNKNBDZsrR4mTBdL2jJVW9w8nmYc3WdmZU5b6cctj9+BBp6vf/tJcGtXtn1fuKO2vBQmF9/c7w9tafnAWgi53CZ/mHGu+pICpLXz4QGavH4FkOZY7R4/+A3ava+KjpoDYD5QzkDOCsAkZcF20Liyjpvjp8lJOKUGzH4G4v9zW/TWW1NcAWhJ6S4+vM4k5eS/61JLt1KMeTTXGQRTh/KFbiIy05askq+LQ4cCMJbYW3kBtdcxGj3CLjBmD88lG3NPeUWCQc0O0wP3nbOA7FyY/a1mhQUM+TOh9yrsaY8lhd6WR4A01DXOEy96fmBbhpwdbWghaSoX3ceKaBVvss3oI8m/Vx4kpOER5yon/jIPuPEkdvjJCZJFBvzpAyf2R0VcbJVZvNKEqPFd0e1kGi3TBpo8gpohYhoJkVD7x6hop5X8D2UJvM+2M1l3NmPiYOIcTJVxgkrk06GCJR2420mam5eMyRGk588xYSnugZlJSQA/Jzgn1
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAMVOhdHFk8NeQT4ffS6OxA90wtbg9Bz00EqQjrlgFYO0nKxkcj8vVNCPJUlcpgK318YJY3SO4+kCql0EyEtiZ+Beu6PnLpViy9Lee/GzI4Xobz9zq5SI6oCn1PqeBat395WGkyZiZRfqu/dBHVbeFN+vkHyZFX/eDHtmUhDTiCM9cPahikze/lL0Ud4QmV/dSoFGfKsR9A16RzJjZHo4UtXKE/HpdJAsIiuRfK5svsY3GVYjaO9tfamn93o1Pab8KvrlVgFjVFIjMN/zKICyfAErDoT1Q+PJ64D7NqN993y1o8th57GBs/zQgb1pu1MbooEH0jHqeTBeuJ0XDlFeeQvxjunUceSZvCOzzwlqVh19kI4DHepwpcmvfRENW9KXkocm6Clm3JY0DFb4Nv+DQogxWNq1TD28GTzxmXUw01+UvRZYKZZ9ElGr2jfyVj5bxvEGUKfB2KrLNNPwt59CWt/2GoPryISil9vXyKpZuHwxJ4nOBAZZUChUr8Awf5fskSng8fm70vXCbm62ko8Mxnz65+vS/m2CFVEvQD34ZNxsXkFXjrfCzs51A9XjfZk+H0cknvzYuwQo6IeHoiJrctEFm4Fdpmg6YTCdSGFtR8gaLsguJoCrJQY97QZhBkHAe6qs0eF7sQr1nM5h+Dgvqz6MUSMxlHbCO/ZlP+ku9BL2+eep/YWxoai1Ch+kg0SUDu3SJS3N0aYieujO0BFqXnqBXHdxPjew0eQfSur9GEJZ48C3hVgttaNy11uvISqXitUj+KpTHRSvrfbVApHkW7
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
    type: Opaque
