cluster:
  extraManifests:
    - https://raw.githubusercontent.com/nmourapt/homelab/main/kubernetes/omni/templates/manifests/argo_manifests.yaml
    - https://raw.githubusercontent.com/nmourapt/homelab/main/kubernetes/apps/_applicationset.yaml
