---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: es-oidc-secret
  namespace: elastic-system
spec:
  encryptedData:
    xpack.security.authc.realms.oidc.oidc1.rp.client_secret: AgBW6gJ8Mug1LRf9mPC9HMl3SL2SP4XkrIZjMiGLsXTB9WzNCmtOVRcKledvyh2e7naVvhW8OCCw66ipceLw62E1dT801BHMKyf2YBDtIQlnffhHy7GDbu5zl7rIptKBJObwVjNFPfBZ0fK0z1rfkCoNxDYCAxsUmETpO04PqVdI1VDVtWM1+kLSZn26yhAgkBpSt5wEVPDQMzwG5yeTt92/n6GLkXrqL2vmEo8BlcYg+39Gn0R+lgmIRzl/BcY8KtykYn1IiCcfGAaFgh+8TFZi29bloGG/p59G50+3Dl2x1zJ40eFsdBkpUVqfKAwdBnitG1G4XVawP/9XF0+2BE2YZQ/6qQjxHzNxiHPkBa9vdYIDIJF7rQb7ygfxU16M6n2pidUcAtizGk6PTa73yeAkBKZjHPxILzrYbq4HKSImjsUEcd+J6cYIIM4/a9MXdEwklbpiffttFTAosazP3Dh93FYi2L6i1UwQDHd/i42HHrD0cFa89h7rX2K9+Q4otAP3bzU6jcHgRfzhtIVrrosHvi7+UFYOGnkSHUnWk2Zcvd3Zqkn/x7B2YzFuCFxQiUt2PzM0OV0D+Rr2GAEehTgKcMMGFvmT2/GP+F+eOuGmxZ0JasifqnjdjKaQrQy9XJz2gmWS27TP6Rg9DzT0LaICT1V3HVmy0xLz97rBv2KHw/Nwm667T/oM6iWb9dYpwz7XnD/qWvQdZJtBF3fslUI4wb0GSfQeT7Nh6Tg3rcn/++mRq3NsFVr5XPgf2dcPvjaxF5Vw+HosytTeXiVFCTLz
  template:
    metadata:
      name: es-oidc-secret
      namespace: elastic-system
