apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-gpu

resources:
  - namespace.yaml

helmCharts:
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts
    version: 0.34.1
    releaseName: intel-gpu
    namespace: intel-gpu
    valuesInline:
      nodeSelector: {}
      nodeFeatureRule: false
      sharedDevNum: 1
      enableMonitoring: true
