---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    oidc.cloudflare.clientSecret: AgCzSol4d0keNkzgGHW6bybAFGpbjvsJUnJFQfh3sgdRaG1HPOW7/MFBF0i4Pt6Hx1rNUAyYWlDHn4dXTPnskOwfA0n73OfQ+6M3zOGnyEORFqbw1R6s3K9ISrmVG2TmXqyBlPoXnHBRlr7r7jtsDZkSemPNNvVhkLhw3po7ZfduA4YZJ4hxzznx7+usZO5kwNbPFifZaRyUngU0jGWFD9/P+F/mDyQ5aepl5/GHIQR0yILaIlYUZggl1LE1NnZZn8z7Z1uDCRBiXYEHdiEGxMKx6mKGsNIijSyMUcqwsbNEjy5ZcZYii82fJoVwGRrxOB+aUlN0OU4HiJQUwihjxt1OnARwmzEDAaHLhRlgapv7rey/d2knpiZwfVHnMZnWTWTdkLd0DZzY7Eci32/V4kt1nyCmQHajv9P60MXd6ibyLChsOYIIf4UAszZAtmFZFjU92mx7wh/YQtPUovijkkiI+x/l+BBrQODQbA3GVk56uOe8K9d87s2CKT+HScRHYID77wUF7pZ1Zat3pLdzd3/B78OJUpnowS7Rh45xTKQhO9lkg6fZPhdPrYOsCl/aRlCf0BTju04lE+ZsjsKP5FjKclc3fObdFznz1hBZ6SY26AEM3BIGcJGP4x0R44Q6sb91YIDVLvLcKAikC0QMuaIcB5smb1+k9fFcZvasmj5VeFbjaVZP3I9orNEYGMrLit7grGHm0p0K5y4IFHYcUAMXGHXVKpau5j8p2tcYeJNYpTx9d4cuI0dgHWvE736NhUoTLdMuzV3on8aK4BXsoSNm
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
