---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.cloudflare.clientSecret: AgAhCR0NeV+SaLXcoYGznKVoXLsAMaGcT7sSpoPGs7DoAquXxDOuqtSNnRnLErnIFwMwAvPAj6PhVd6aoE62ACwbh08DqsLjw/vthpb7bZSmKKRAiHVcWpCpm8wAEdx6h4vifJPP1PJ95+FdJg9CGbo3rDhqb/bPsVfieFAWwly+2W67UkaCIucCjT6BB+HlrzaukhbZ3aDdl0xyPkzVgm3y5O+P4Jl1WKEGGJPn0hEzwljs5tRQK9KSlp6sx0n12IY/t7puohhKhmD4bF5807vrwpW4K4HBIK0dmZs5GhFFkqXg4ZGTH9vojaSSMxSKTi3t2G5opUfk+oc47vw7vUSpIhHQdbhGjSESSL17wv7+mHOnW9pIbQTQbojv38JDD+7Nq8gzoyHzPAh9CuNJ/PXDI6elDJHXW2B4iWZLKtU0UGKLeD6TElHooNcLnd1S+ITC4c6cmFXBniHaBSj1BVjLD84nxbhPrIW/B6O0Gml6EpggnYB4DVuXtxoIyMZ4szfwpL/f1ihYj8C8DC7CfbxrQyH/BpkyRzOgQ59McSfL/pIHmkiy3VlOHDEPBTdR0oDCOQq9KThh5nU9Me9H/J3fDMPnvO3Avo9HY1GZuU4mZsOM7W6qhRtFFcph/YliH6oNG+VSVYk0oXPiyhfCUivVi7Jijbelmsr+yndFlRu/MyxwAhw+/CqTo8b2+0aanq5SU18FQK8LnWnooNEj/jFXxv6fm13EFedFUjqhpvVKWLlAv3X9kKzZkO2nsNJ82OX2YXkxUfHPRAL/Vgsnc8Jl
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque
