---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    tunnelToken: AgB4A0zekr21UyE2qBOMLID81YuELZAwiDk8sa74vwVulOLuRTa3t0pubA3N+MFFwJrbCUA05F1oXZyszXRqlCSbYJWGrC0kfCSTzGHng3XDvyxy5O1yuEgThBKILK2uMk7xPawwlp9EtmKjkeaSqyycka8kpFgZSJuB956jDwfz45xMaIU2P+KNboRzUaAqPVw9UJj3qFaNtFwT7a2SdWjIbQ2bZu+JrPfddIlGWPJ0NbhmdZ0HVg3BCmy5+etA90InErit9qSxGfztQ4Xdg1ahkcYfpXxOQzxCRYTpR/Qar5i38U24vBqMGdnC8w94CUz/dG/gG2/2stOh5H11tb3eRB0N9xt/YAt19vtE5kmqhWBbmXCdJ3f0fuzDqINiW5t2DHTLvLFukeLiB8yMpx7IjMxu6Izn3oofExntKGAK4ownmjzzGRt8ROq7/S2SHUpUEiIpNGI4ejuaCUEceUToyvPEdKYBNpsWVFIZZpXjkH7i16hfS99Q9lREqiMdfCtd8jgRA+aAEG5JFHZ6k3UYZ1AAdOeeB5bj+30+UltAA/sUZZiKSM4bT6dISffh1HC1uXvFW7X150p/3CQh3LkzNzYRt2XLzNxtJGTWuiDFxyoUU6wOpIoN9Zg2s2l82xp6vwMxpS7nnjZwZBP+W5qPeyMD7bxd8gcuup3H5j6EiY99C92bvdhORzfijN+5baed+OKG7rww1cqAoSW4mfaDLLnDIxszUAoNDZ1vYo2Hj8KzpM+Udi9eLJ6fhCv1ccfN1bZOCM/dcI8ISebig8zdRaaxdT+Awxj23wzEdV2kkqA5YMK2gw0T0ECYZ7YF2i51jBhXnRzJotBQESiDLjqQgbz41Qx1PjnUIztMR1EuoRtjTz23s2ypNmP3+ANAUs7nXGAc2mLuy9Gyobv5yI5tkvuT64kXEnBqSm596yT/ThXny8cB2lOxKnuivwp1wc4LRuiy5PFcYAXTvJ13tbx0efVWMLBjO7yFNPabOJaN97xnSH/kgQEtuvm6f+wJW9M=
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
    type: Opaque
