apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflared
  labels:
    app: cloudflared
spec:
  selector:
    pod: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
