---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-config
  namespace: cloudflared
spec:
  encryptedData:
    tunnel-target: AgBfXCUdm+K3HPKgdf9Kdx96i6PaGDc1R0gMJV84U46jQccAQkI99kwnsFrSH3Lth6BlYyN1O4jqbXum7MYGl9vqiidIhMxfe2Vu5VfjqzlPagtS8CaBLsIgxH5WJObVO8MLIK2iVd3BSpZ05K1obPBzCZcE86o7xYOp6NBy5MajekC2ees26p8eEpYWIntKRqKLOFeZ7EZ7dObozzYDdQTY2WmenXxLPKHJOUNKgqj/B3QTpE9lUuqYDZpy3MMFMODqpZvCvqni80vGWjM+QsqHd8+TBIW+GhGr7sfVEEm/g0vm52KBySdATa8Q2Xpy+hnjUMliFh9/oAOX22cFH+BZozXowi28UHXnVcTK/ZEztavUbwKjnM+OWnTRRVXgglDuE/TujITTNWkL6BfeF2YJZpG+wvhsgVfILT4vFFlZfpl1vBJYNqYGzOFlDH3xXsBIMYDxI4dtAuMBPYmI5rG4SyPotwmFx2M/4fzFqQNwrm3mzp3rbRBVP0XywRxty8bTs4zNJ1qdR4GwA/nQw5IYZScJ0hp3RpNNrXRlEKvJTBzRrt7enHrQPZT9iE+ZRkXhMdsVLjJOBkeo453dc4G1oiYejqv+LAfvU8mvHNSMB7kW09nr8FB8IeRGHXeQuUXq8VKfk0ishWsH40JNzr75evs5RhBcz5lpmudNQnUCkIU/1WyMpIOMfI7V2DWfvDDinHTXuIUCCzg3U0r5DoNaTuxSvFKq4Qt/bnFkZftOVmDLievXjMFjk3t8hLWvf8coqzdBgA==
  template:
    metadata:
      name: tunnel-config
      namespace: cloudflared
    type: Opaque
