services:
  netboot:
    container_name: netbootxyz
    image: lscr.io/linuxserver/netbootxyz:v0.7.6-LS222
    restart: unless-stopped
    environment:
      WEB_APP_PORT: "3001"
      NGINX_PORT: "3002"
    volumes:
      - /volume2/docker/netbootxyz/volumes/config:/config
      - /volume2/docker/netbootxyz/volumes/assets:/assets
    ports:
      - "3001:3001"
      - "69:69/udp"
      - "3002:3002"
    networks:
      - prod_net

networks:
  prod_net:
    external: true
