apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seerr

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingressroute.yaml
  - seerr-secrets.sealedsecret.yaml
