---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seerr-secrets
  namespace: seerr
spec:
  encryptedData:
    DB_PASS: AgCjtMrvf3y34XJVNtX95ES+mOdtaCx1EF4XpXw1ob1OFUl6OpYiVPDvxd8xIRU9mDcFBeq7xjCveKPbBkqDpA5XUGKR3g0XeJnhc6S2J94+RNNF3Drx39mh/EAaB8p6h2nSM73mZNb3lhkl1mY7VdO5Uz+kv430ygE+UL7m5Jml/yxIcsDsXjDT/8lVELmKh1Vf+qCLEN9/ZYmYWPNxPBuouzTwaxBByaAdgESK4reznTvDHfbBkKpFayonghHwKD6qh/XJCdEgb4UU5+2RURSua0+g5r1u7aCUN43K+g00Dr+B0INXkJua7x4iCs6+qhvU/oWW0BWZPvYN0+zWETEQn1oJ2kOI01yPoFf6KqpqGri601MuN3PzINabrRBDEiOJN2LrwTpkPF8DaKj5UQFNRu+PJb7plmxe/l/40+cr3wxyV7FM+uOaWNqLXfouRlao+QQvkzpFQpddibbenzZvWffp+Lns0mJIpfmXxe6udajFn9TT8t1OlWqgAqUhqQTJpdsooe2hHddFj4IbaeVKcYri1pJsJHr9t4FMzUWS/EefKuWw41iMz2VQnTuabPXiViwv0A78+U+Y52bxasMHSO0v1+KvSlbCmPu0iFrxLxE9ENsjj4ubC5iKbHzedY3692rDnt+2B6DaRaKkGp90gHC6roFKsswaZky7nEePOqGQywXib2/eSocmfnfRIECwcdIN5zcGv0UyREev4R/2sWY7ENnIyRzt0565ncJeag==
    DB_USER: AgBdEFhbU/8SrrCj/AqYDO0BANAyuDuNRWrvOK/gKK4N7Y2+Jxf2UgsGu6kzOcfzZhh3Uodi4zGLawOKAEIBm+DRQRpFaex4l/I9Y0KgGDzzWyRygeC0halfgBirXAXklrDYKEalkqzYIV2SPbmoKBN9iWuhbLygWacnYN2eERPDJ50epDvVOFpLW/FnVkuwkt6b7mU0UoPyAqqj/zATMSCfhPYUheTSqjnz7utHM9whR3q9LcGNC4HV1I0J6nvRyX5BpNHFizLkHy7qeOzeeoQoK4oLVsncuIBhTlFh7Z9pbzw2p93DXSHOLiDZBKvW+UR0EPcOddqSijhgUJLMRuZPilCrV3NMIHJETKnDxRU4rifujnZX0YHhUOktNIbyg+oJ6fevwSFKGKSw7vLAIoPDO74W2pTfXw94lfRGuZKMOpbuChgcE+e7IbfpBZI3h6wCJOXOmuuVhCZym84Fobuitex7jOBqbmh2i77znxrP2QftO4ryzuO1RnrHNkVoVHhIhIW5wUXG+VMSEBG24+2p9juZc5K2mC35xEtlztpxfUw5MWTF6GiOrF+K7yiR+w8f5ssX9yEM02s0I/lPAuWJR5melErFRBig8JR4MTYolKADVaJZ3vGW8DBJxMgGyyzkV0TvQGptEKoBM4oJJtjSGh0wLqHYkRb7NkYgc5bKav73MijnejE8qljyMWMnpBuA7rslfk2gLT+h
  template:
    metadata:
      name: seerr-secrets
      namespace: seerr
    type: Opaque
