apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: seerr
  labels:
    app: seerr
spec:
  type: ClusterIP
  ports:
    - port: 5055
      targetPort: 5055
      protocol: TCP
      name: http
  selector:
    app: seerr
