services:
  omni:
    container_name: omni
    image: "ghcr.io/siderolabs/omni:v1.4.7"
    restart: unless-stopped
    devices:
      - /dev/net/tun
    volumes:
      - /volume2/docker/omni/volumes/db/etcd:/_out/etcd
      - /volume2/docker/omni/volumes/db/omni.asc:/omni.asc
      - /volume2/docker/omni/volumes/db/sqlite:/sqlite
      - /volume2/docker/certbot/volumes/letsencrypt/live/${DOMAIN}/fullchain.pem:/tls.crt
      - /volume2/docker/certbot/volumes/letsencrypt/live/${DOMAIN}/privkey.pem:/tls.key
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    command: >
      --account-id=${OMNI_ACCOUNT_UUID} 
      --name=omni
      --cert=/tls.crt
      --key=/tls.key
      --machine-api-cert=/tls.crt
      --machine-api-key=/tls.key
      --private-key-source='file:///omni.asc' 
      --event-sink-port=8091
      --bind-addr=0.0.0.0:443
      --machine-api-bind-addr=0.0.0.0:8090
      --k8s-proxy-bind-addr=0.0.0.0:8100
      --advertised-api-url=https://${OMNI_DOMAIN}
      --siderolink-api-advertised-url=https://${OMNI_DOMAIN}:8090
      --advertised-kubernetes-proxy-url=https://${OMNI_DOMAIN}:8100
      --siderolink-wireguard-advertised-addr=192.168.202.1:50180
      --auth-oidc-enabled \
      --auth-oidc-provider-url ${OIDC_PROVIDER_URL} \
      --auth-oidc-client-id ${OIDC_CLIENT_ID} \
      --auth-oidc-client-secret ${OIDC_CLIENT_SECRET} \
      --auth-oidc-scopes openid \
      --auth-oidc-scopes profile \
      --auth-oidc-scopes email \
      --sqlite-storage-path /sqlite/omni-sqlite.db
