apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radarr

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - nfs-pv-pvc.yaml
  - ingressroute.yaml
  - servicemonitor.yaml
  - radarr-secrets.sealedsecret.yaml
