apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-radarr-synology
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: radarr
    name: pvc-radarr-synology
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-synology
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: pv-radarr-synology
  storageClassName: ""
