apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
spec:
  type: ClusterIP
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: http
    - port: 9708
      targetPort: 9708
      protocol: TCP
      name: metrics
  selector:
    app: radarr
