apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarr

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - nfs-pv-pvc.yaml
  - ingressroute.yaml
  - sonarr-secrets.sealedsecret.yaml
