services:
  traefik:
    container_name: traefik
    image: traefik:v3.6.8
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "1734:80"
    networks:
      - prod_net
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      
  traefik_cloudflare_companion:
    container_name: traefik_cloudflare_companion
    image: tiredofit/traefik-cloudflare-companion:7.4.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      CF_TOKEN: ${CF_TOKEN}
      TARGET_DOMAIN: "${TARGET_DOMAIN}"
      DOMAIN1: "${DOMAIN1}"
      DOMAIN1_ZONE_ID: "${DOMAIN1_ZONE_ID}"
      DOMAIN1_PROXIED: "true"
      DOMAIN1_COMMENT: "added by traefik-cloudflare-companion"
    networks:
      - prod_net

networks:
  prod_net:
    external: true
